#!/bin/bash
total 24
-rw-r--r-- 1 0 0  66 Sep 28 07:26 0-current_working_directory
-rw-r--r-- 1 0 0  49 Sep 28 07:37 1-listit
-rw-r--r-- 1 0 0  16 Sep 28 07:40 2-bring_me_home
-rw-r--r-- 1 0 0  63 Sep 28 07:43 3-listfiles
-rw-r--r-- 1 0 0 431 Sep 28 07:46 4-listmorefiles
-rw-r--r-- 1 0 0  12 Sep 28 07:47 5-listfilesdigitonly
-rw-r--r-- 1 0 0   0 Sep 28 07:45 cat
